### PR TITLE
README: point to all benchmark results

### PR DESCRIPTION
**Pull request by foxpy**
Previously, we have only been pointing to i7-11850H results, leaving everything else behind the scenes.

Now, when user clicks on link to results — user sees all benchmark results at once.

### CODE REVIEW

**Comment by MBkkt** [comment]
I think we want a list of benchmarks here, can you add other processors, or I will make it

**Comment by foxpy** [comment]
> I think we want a list of benchmarks here, can you add other processors, or I will make it

If we want to maintain links to all processors, we probbaly want them to be added automatically to README. Otherwise, we will have to manually add links after every benchmark result contribution there is. Sounds unpleasant.

**Comment by foxpy** [comment]
…I have deleted a wrong branch from command line.

**Comment by foxpy** [comment]
@MBkkt anyway, I propose two solutions:
- merge this pull request as is;
- automatically update README after successful `./run.sh` run.

What do you like the most?

**Comment by MBkkt** [comment]
@foxpy How can we correct automatically update readme?
We can make a separate readme in future/result hm

**Comment by foxpy** [comment]
> We can make a separate readme in future/result hm

I will do that

**Comment by MBkkt** [comment]
We also need to modify `run.sh`
something like
```bash
echo "- [$proc]($proc/)\n" >> future/result/README.md
```

**Pull request merged**
